### PR TITLE
feat: cleanup introspection, enable introspecting large database schemas

### PR DESCRIPTION
**Pull request by jensneuse**

### CODE REVIEW

**Review by StarpTech — APPROVED** [review]
Great improvements

**Comment by fiam** [comment]
I’m testing something. We need to be careful to not leave the prisma process hanging around.

**Review by YuriBuerov — APPROVED** [review]

**Comment by fiam** [comment]
All good, the cancellation of the context should take care of killing the subprocess

**Review by fiam — APPROVED** [review]
LGTM

**Pull request merged**
