### PR TITLE
chore: remove new api introspection

### PR DESCRIPTION
**Pull request by devsergiy**
This reverts commit 0f070bb28b37c4cfe30b356f2c11c1f69d1bd903.

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jensneuse — APPROVED** [review]

**Review by fiam — APPROVED** [review]
LGTM

**Comment by msaktor** [comment]
Hi, can you shed a bit of light why was the `openApiV2` removed?

I am evaluating Wundergraph for our upcoming project and I like it a lot but the new OpenAPI introspection kinda worked with our specs whereas the `openApi` fails to parse the json document.

Are there plans to bring the new introspection back?
Thanks!

**Comment by msaktor** [comment]
Thank you for a quick reply Jens! That sounds great!
Another thing I've stumbled upon is a bit inflexible way how to add custom headers = if I need to use HMAC, common part of the signature is the [endpoint path](https://learn.microsoft.com/en-us/azure/communication-services/tutorials/hmac-header-tutorial?pivots=programming-language-csharp#sign-an-http-request-with-c)

So it would be nice to have access to the request object = `headers: (builder, request) => ...`
```
const fooService = introspect.openApi({
	apiNamespace: 'cs',
	source: {
		kind: 'file',
		filePath: '../foo-service.json',
	},
	headers: (builder) => {
		const headers = signRequestWithHmac();
		return builder
			.addStaticHeader('X-TS', `${headers['X-TS']}`)
			.addStaticHeader('X-Key', headers['X-Key'])
			.addStaticHeader('X-Sig', headers['X-Sig'])
	},
})
```

**Comment by jensneuse** [comment]
You can use an onOriginRequestHook, check for the host in the URL and add a signature if needed: https://docs.wundergraph.com/docs/wundergraph-server-ts-reference/on-origin-request-hook#__next

**Pull request merged**
