### PR TITLE
fix: generate all required templates

### PR DESCRIPTION
**Pull request by JivusAyrus**
#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by JivusAyrus** [comment]
Updating examples and docs in a different pr. So that we can release the packages first.

**Review by fiam — APPROVED** [review]
Small diff, but big QoL improvement - LGTM

**Review by Pagebakers — APPROVED** [review]
Great! Docs will be updated in another PR?

**Comment by JivusAyrus** [comment]
> Great! Docs will be updated in another PR?

Yep, so that we can merge as soon we release?

**Pull request merged**
