### PR TITLE
fix: fix wundernode ui

### PR DESCRIPTION
**Pull request by JivusAyrus**
Before the fix
image

#### Checklist

- [ ] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by StarpTech — APPROVED** [review]
LGTM

**Review by fiam — APPROVED** [review]
LGTM

**Review by thisisnithin — CHANGES_REQUESTED** [review]
Can you check for mobile screen?

**Comment by Pagebakers** [comment]
I'm not a huge fan of the description of the docs link. "empower your WunderNode"

Maybe change it to the new description of the docs website?

"Learn more about how to integrate APIs and build backends with WunderGraph."

What do you think.

**Review by thisisnithin — APPROVED** [review]

**Pull request merged**
