### PR TITLE
feat: make WunderGraphConfigApplicationConfig.cors optional

### PR DESCRIPTION
**Pull request by fiam**
If nothing is provided, default to allowing all origins

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by StarpTech — APPROVED** [review]
LGTM

**Comment by fiam** [comment]
@jensneuse No, with this PR leaving `WunderGraphConfigApplicationConfig.cors` will always omit the CORS headers from the responses. Would you prefer if we allowed all hosts by default? It's a 1-line change.

**Comment by jensneuse** [comment]
> @jensneuse No, with this PR leaving `WunderGraphConfigApplicationConfig.cors` will always omit the CORS headers from the responses. Would you prefer if we allowed all hosts by default? It's a 1-line change.

Yes. Allow all origins by default.

**Comment by fiam** [comment]
> > @jensneuse No, with this PR leaving `WunderGraphConfigApplicationConfig.cors` will always omit the CORS headers from the responses. Would you prefer if we allowed all hosts by default? It's a 1-line change.
> 
> Yes. Allow all origins by default.

Thanks for the clarification. I’ll change it.

**Comment by fiam** [comment]
@jensneuse There are many ways to set the default to allow all origins, so please let me know what you think of this way and I'll update the PR with the appropriate documentation changes.

**Pull request merged**
