### PR TITLE
fix: live query support in generated web client

### PR DESCRIPTION
**Pull request by xzyfer**
This regression was introduced in #78. The client SDK expects this properted to be `liveQuery`.

See https://github.com/wundergraph/wundergraph/blob/b0bd559d8f2e2785f5f27029bf113da19e13dd65/packages/sdk/src/client/client.ts#L253

#### Checklist

- [ ] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jensneuse** [comment]
@thisisnithin @JivusAyrus can you verify this?

**Comment by thisisnithin** [comment]
> @thisisnithin @JivusAyrus can you verify this?

Yup, the interface has `liveQuery`

**Comment by StarpTech** [comment]
It also looks good to me. @thisisnithin did you verify the behaviour?

**Comment by StarpTech** [comment]
@xzyfer thank you for the fix.

**Pull request merged**
