### PR TITLE
fix: use correct import on react hooks template for server imports

### PR DESCRIPTION
**Pull request by RayHughes**
The `@wundergraph/sdk` import does not resolve ` RequestOptions`, `MutateRequestOptions`, `SubscriptionRequestOptions`, and `Response`  functions. These functions can be found at `@wundergraph/sdk/server`

## Motivation and Context

Working on generating client and realized that the imports could not be resolved on the template.

## Marketing Changelog
- Corrected import on React Hooks template.

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by fiam** [comment]
cc @Pagebakers

**Comment by Pagebakers** [comment]
Thanks for the PR @RayHughes, we don't recommend using this code any longer, it will be removed in future releases. And recommend using the SWR or React Query client (separate packages) instead.

It'd be better to also not import from /server in here or at least use `import type {}` to make sure only types get imported here and no other server code.

**Comment by Pagebakers** [comment]
Definitely, please follow these instructions (apply to expo, but also regular react native)

https://docs.wundergraph.com/docs/getting-started/expo-quickstart

**Comment by RayHughes** [comment]
> Thanks for the PR @RayHughes, we don't recommend using this code any longer, it will be removed in future releases. And recommend using the SWR or React Query client (separate packages) instead.
> 
> It'd be better to also not import from /server in here or at least use `import type {}` to make sure only types get imported here and no other server code.

Pagebreakers, 

WG/SWR or the actual SWR library. We're having trouble getting our generated client to work in RN

**Pull request closed without merging**
