### PR TITLE
feat: add a tool to sort imports project wide

### PR DESCRIPTION
**Pull request by spetrunin**
#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jensneuse** [comment]
@spetrunin cleanup + merge or throw away?

**Comment by spetrunin** [comment]
@jensneuse it lacks a pre-commit hook and ensuring that tool is installed

Want to have it, but was not having a time to finish it

**Comment by jensneuse** [comment]
It's getting stale. What should we do with it?

**Comment by spetrunin** [comment]
I will update it soon

**Comment by spetrunin** [comment]
closed in favor of https://github.com/wundergraph/wundergraph/pull/242

**Pull request closed without merging**
