### PR TITLE
test: add tests for webhooks example

### PR DESCRIPTION
**Pull request by fiam**

### CODE REVIEW

**Comment by fiam** [comment]
Changing to draft while we decide how to handle secrets during tests

**Review by StarpTech — APPROVED** [review]
LGTM

**Review by spetrunin — CHANGES_REQUESTED** [review]
Tests are failing

I suppose it requires example env file?

**Comment by fiam** [comment]
@spetrunin Thanks for the heads-up, that was indeed the problem. Good catch!

**Review by spetrunin — APPROVED** [review]

**Pull request merged**
