### PR TITLE
fix: custom int/float scalars usage in arguments (#427)Co-authored-by: Alberto García Hierro <alberto@garciahierro.com> Co-authored-by: Sergiy <818351+devsergiy@users.noreply.github.com> Co-authored-by: spetrunin <neyasut@gmail.com>

### PR DESCRIPTION
**Pull request by OLingard**
## Description

After the required to Graph-Go-Tools in the PR [here](https://github.com/wundergraph/graphql-go-tools/pull/456), we can now look to fix the issue with `customIntScalars` described [here](https://github.com/wundergraph/wundergraph/issues/284). The goal of this PR is to adjust the `ArgumentConfiguration` so that the upstream origin has an understanding of which arguments have been replaced with the `Int` or `Float` types.

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by OLingard** [comment]
@jensneuse, I've added the PR here with my current efforts. Once it got to debugging the requests being sent to the Go server, my skills were limited due to not debugging the Wundergraph server before. 

I've added the changes to `ArgumentConfiguration` which looks like it is set up correctly during the introspection however there's a bug somewhere which I'm missing.

**Comment by OLingard** [comment]
Hey @fiam, hope you had a nice New Year! Just double checking where this fits on your timelines? Not too sure about how to proceed with this and it's blocking us from using Wundergraph for our application.

**Comment by fiam** [comment]
@OLingard Apologies for the delay and thanks for the heads up! We've discussed this feature and we're more than happy to accept your contribution. Could you please fix the conflicts so we can move forward with the review? Thanks!

**Comment by OLingard** [comment]
Hi @fiam, updated so it is in sync with the latest main.

> I've added the changes to `ArgumentConfiguration` which looks like it is set up correctly during the introspection however there's a bug somewhere which I'm missing.

Just re-adding the comment I made to Jens above, hopefully should be a minor bug but my Wundergraph knowledge isn't deep enough to fully crack the final bug and unfortunately I'm on holiday for a couple weeks from tomorrow. I'll keep an eye on this thread though and try and make any changes needed.

**Comment by fiam** [comment]
> Hi @fiam, updated so it is in sync with the latest main.
> 
> > I've added the changes to `ArgumentConfiguration` which looks like it is set up correctly during the introspection however there's a bug somewhere which I'm missing.
> 
> Just re-adding the comment I made to Jens above, hopefully should be a minor bug but my Wundergraph knowledge isn't deep enough to fully crack the final bug and unfortunately I'm on holiday for a couple weeks from tomorrow. I'll keep an eye on this thread though and try and make any changes needed.

Thanks for the quick reply! Could you please elaborate on that bug? Is it uncovered by the test suite? If we can easily reproduce it, we'll find a quick way faster.

**Review by jensneuse — APPROVED** [review]

**Comment by OLingard** [comment]
> > Hi @fiam, updated so it is in sync with the latest main.
> > > I've added the changes to `ArgumentConfiguration` which looks like it is set up correctly during the introspection however there's a bug somewhere which I'm missing.
> > 
> > 
> > Just re-adding the comment I made to Jens above, hopefully should be a minor bug but my Wundergraph knowledge isn't deep enough to fully crack the final bug and unfortunately I'm on holiday for a couple weeks from tomorrow. I'll keep an eye on this thread though and try and make any changes needed.
> 
> Thanks for the quick reply! Could you please elaborate on that bug? Is it uncovered by the test suite? If we can easily reproduce it, we'll find a fix way faster.

Hey @fiam, sorry for the slow response, been out of the country for the past weeks. I've updated the PR with the latest changes from main.

Regarding the bug, it looks like the config inside the generated `wundergraph.config.json` is what is expected when a custom scalar is provided. The argument configuration of an affected field looks like:
```
        {
          "typeName": "Query",
          "fieldName": "testField",
          "argumentsConfiguration": [
            {
              "name": "id",
              "sourceType": 1,
              "sourcePath": [],
              "renderConfiguration": 0,
              "renameTypeTo": "ID"
            }
          ],
          "disableDefaultFieldMapping": false,
          "path": [],
          "requiresFields": [],
          "unescapeResponseJson": false
        }
```

However in the debugTransport, it still doesn't seem to edit the origin request to include the renamed argument type. In other words, I still get this error returned from the origin:

```
errors": Array[1][
    {
      "message": "Validation error of type VariableTypeMismatch: Variable type 'Int!' doesn't match expected type 'ID!' @ 'testField'",
      "locations": Array[1][
        {
          "line": 1,
          "column": 61
        }
      ],
      "extensions": {
        "classification": "ValidationError"
      }
    }
  ],
```

I'm replicating this with my upstream server so I'm happy to jump on a call to explain this further and to debug this together.

**Comment by fiam** [comment]
Thanks for the update @OLingard. This week we're a bit busy preparing the beta, I'll take a look no later than next week.

**Comment by OLingard** [comment]
Hi @fiam, is there any update into timelines on this?

**Comment by OLingard** [comment]
Hi @fiam, sorry to push, just trying to gather timelines on this one, is there any update?

**Comment by fiam** [comment]
Hi @OLingard - Sorry about the delay, this fell through the cracks and we haven't given it a good look yet. Do you have a repro that I can run myself and try to fix the remaining issue? That would help speed things up a lot. Thanks!

**Comment by OLingard** [comment]
Hi @fiam, I've added a quick demo here showcasing the issue here: https://github.com/OLingard/Wundergraph-Bug-Showcase. I'd just copy the example into the examples folder in the Wundergraph repository to try it out.

As mentioned prior I'm not on top of the inner working of the code base so I might be missing something in my set up or something else which is simple.

**Comment by fiam** [comment]
> Hi @fiam, I've added a quick demo here showcasing the issue here: [OLingard/Wundergraph-Bug-Showcase](https://github.com/OLingard/Wundergraph-Bug-Showcase). I'd just copy the example into the examples folder in the Wundergraph repository to try it out.
> 
> As mentioned prior I'm not on top of the inner working of the code base so I might be missing something in my set up or something else which is simple.

Thanks a lot, that's super helpful!

**Comment by devsergiy** [comment]
Hi @OLingard 

I have made additional fixes, and now no need to modify a query, it should work as is

```graphql
query HorizonAndHygraphDemoProduct($sku: Int!) {
     horizon_product(sku: $sku, strict: false) {
         title
     }
}
```

**Review by fiam — APPROVED** [review]
LGTM

**Review by jensneuse — APPROVED** [review]

**Comment by OLingard** [comment]
Hi @fiam, thanks for looking at this! Almost reading to go now, one SKU which should return data is `14187821`. I think we're close however there's an issue with the query being passed to the backend. The stack trace of a request using the operation in the demo is as follows:
```sh
--- ClientRequest start ---

GET /operations/ProductDemo?sku=14187821 HTTP/1.1
Host: localhost:9991
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cache-Control: max-age=0
Connection: keep-alive
If-None-Match: W/"2778056214337555698"
Sec-Ch-Ua: "Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36





--- ClientRequest end ---

2023-03-07T10:19:25+00:00 INFO: incoming request {"component":"@wundergraph/server","reqId":"314274f0-5460-b941-e29f-381d4ebf0427","req":{"method":"POST","url":"/global/httpTransport/onOriginRequest","hostname":"localhost:9992","remoteAddress":"::1","remotePort":56364}}
onOriginRequest { variables: { sku: 14187821, a: false } }
2023-03-07T10:19:25+00:00 INFO: request completed {"component":"@wundergraph/server","reqId":"314274f0-5460-b941-e29f-381d4ebf0427","res":{"statusCode":200},"responseTime":6.246208995580673}


--- DebugTransport ---

Request:

POST /graphql HTTP/1.1
Host: horizon-api.www.coggles.com
accept: application/json
content-type: application/json
x-request-id: 314274f0-5460-b941-e29f-381d4ebf0427

{"variables":{"sku":14187821,"a":false}}

Duration: 228 ms

Response:

HTTP/2.0 400 Bad Request
Connection: close
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type, X-Captcha-Type, X-Captcha-Response, X-Force-Rate-Limit, X-Preview-Site-State-Key, X-Chumewe-User, X-Chumewe-Session, X-Horizon-Client
Access-Control-Allow-Methods: POST, OPTIONS
Access-Control-Allow-Origin: https://www.coggles.com
Access-Control-Max-Age: 86400
Content-Type: application/json
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Strict-Transport-Security: max-age=31536000
Vary: Origin
X-Content-Type-Options: nosniff

No query provided

--- DebugTransport
```

The request still works for queries not using the custom int mapping such as:

```gql
query CollectionDemo($page: horizon_PagePath!) {
    horizon_page(path: $page) {
        title
    }
}
```

With a page variable of `/woman`.

A stack trace of running this operation returns:

```sh
--- ClientRequest start ---

GET /operations/CollectionDemo?page=/woman HTTP/1.1
Host: localhost:9991
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cache-Control: max-age=0
Connection: keep-alive
If-None-Match: W/"16680724490209898961"
Sec-Ch-Ua: "Chromium";v="110", "Not A(Brand";v="24", "Google Chrome";v="110"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36





--- ClientRequest end ---

2023-03-07T10:26:05+00:00 INFO: incoming request {"component":"@wundergraph/server","reqId":"309cba00-6260-151e-fda9-e9ec03704dd4","req":{"method":"POST","url":"/global/httpTransport/onOriginRequest","hostname":"localhost:9992","remoteAddress":"::1","remotePort":56444}}
onOriginRequest {
  variables: { page: '/woman' },
  query: 'query($page: PagePath!){horizon_page: page(path: $page){title}}'
}
2023-03-07T10:26:05+00:00 INFO: request completed {"component":"@wundergraph/server","reqId":"309cba00-6260-151e-fda9-e9ec03704dd4","res":{"statusCode":200},"responseTime":4.431583002209663}


--- DebugTransport ---

Request:

POST /graphql HTTP/1.1
Host: horizon-api.www.coggles.com
accept: application/json
content-type: application/json
x-request-id: 309cba00-6260-151e-fda9-e9ec03704dd4

{"variables":{"page":"/woman"},"query":"query($page: PagePath!){horizon_page: page(path: $page){title}}"}

Duration: 46 ms

Response:

HTTP/2.0 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type, X-Captcha-Type, X-Captcha-Response, X-Force-Rate-Limit, X-Preview-Site-State-Key, X-Chumewe-User, X-Chumewe-Session, X-Horizon-Client
Access-Control-Allow-Methods: POST, OPTIONS
Access-Control-Allow-Origin: https://www.coggles.com
Access-Control-Max-Age: 86400
Content-Type: application/json
Expires: Thu, 01 Jan 1970 00:00:00 GMT
Strict-Transport-Security: max-age=31536000
Vary: Origin
Vary: Accept-Encoding
X-Content-Type-Options: nosniff

**Correct Returned Data**

--- DebugTransport
```

Once this bug is good, all will be good on my side! Again thanks for fixing the previous bugs, much appreciated.

**Comment by devsergiy** [comment]
Hi @OLingard 

Could you clarify how you were testing these changes?

As this is unmerged and not released we usually use `testapps/default` or `tesapps/simple` to test such changes with changed sdk

In order to test this change with the simple test app

1. add your api and query to the simple test app
2. make sure to clean `.wundergraph/cache` and `.wundergraph/generated` folders within simple test app
3. run make
4. run make wunderctl
5. after that you will be able to run scripts from `testapps/simple/package.json`

On this branch with the latest fixes I see such query to upstream

```json
{"variables":{"sku":14187821,"a":false},"query":"query($sku: SKU!, $a: Boolean!){horizon_product: product(sku: $sku, strict: $a){title}}"}
```

**Comment by OLingard** [comment]
Yep you're completely right! I had created a new example in the examples folder to test it out whilst changing the sdk package to point to the file system.

Just for the future, it might be worth adding some documentation in the contributing guide about this. It wasn't clear to me how to run and debug a local test.

This works as expected after following your instructions, thanks so much!

**Pull request merged**
