### PR TITLE
fix: incorrectly derived filesystem paths on Windows

### PR DESCRIPTION
**Pull request by fiam**
Use filepath.Join() instead of path.Join() to construct filesystem paths.

### CODE REVIEW

**Comment by fiam** [comment]
This needs to be tested on Windows before merging

**Comment by fiam** [comment]
Windows binary attached, in case anyone has a chance to test it before I do
[wunderctl.exe.zip](https://github.com/wundergraph/wundergraph/files/10367168/wunderctl.exe.zip)

**Review by StarpTech — APPROVED** [review]
Good catch. I think we should also revisit other places.

**Comment by fiam** [comment]
@johnrazmus Thanks for the report. There were several more occurrences of incorrectly used `path.Join()` calls. I've gone through all the occurrences and changed the ones referring to the filesystem to use `filepath.Join()` instead.

Here's an updated Windows binary
[wunderctl.exe.zip](https://github.com/wundergraph/wundergraph/files/10369499/wunderctl.exe.zip)

**Comment by johnrazmus** [comment]
Pathings seem good now, ty!

**Comment by fiam** [comment]
@johnrazmus Thanks for your help! The fix should be in the next release.

**Pull request merged**
