### PR TITLE
chore: upgrade sdk in examples

### PR DESCRIPTION
**Pull request by StarpTech**
#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by spetrunin — CHANGES_REQUESTED** [review]
examples ci failing

seems some issues with ip

**Comment by spetrunin** [comment]
looks like `localhost` should be changed here to `0.0.0.0`

https://github.com/wundergraph/wundergraph/blob/main/packages/sdk/src/testing/index.ts#L205-L208

**Comment by spetrunin** [comment]
@StarpTech this should be merged first https://github.com/wundergraph/wundergraph/pull/499

**Comment by StarpTech** [comment]
@spetrunin #499 is merged

**Review by spetrunin — APPROVED** [review]

**Review by Pagebakers — APPROVED** [review]

**Pull request merged**
