### PR TITLE
chore: update code generation to generate all typescript templates in docs

### PR DESCRIPTION
**Pull request by JivusAyrus**
#### Checklist

- [ ] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Pagebakers — CHANGES_REQUESTED** [review]
Why is this now in 'generate'? 

```ts
  generate: {
    codeGenerators: [
      {
        templates: [templates.typescript.client],
        path: './components/generated',
      },
    ],
  },
```

**Comment by JivusAyrus** [comment]
> Why is this now in 'generate'?
> 
> ```ts
>   generate: {
>     codeGenerators: [
>       {
>         templates: [templates.typescript.client],
>         path: './components/generated',
>       },
>     ],
>   },
> ```

I think its because we have two generators, code and operation.

**Comment by StarpTech** [comment]
> I think its because we have two generators, code and operation.

This has already been answered. It's because of the new `wundergraph.generate.ts`

**Review by Pagebakers — APPROVED** [review]

**Review by StarpTech — APPROVED** [review]
LGTM

**Pull request merged**
