### PR TITLE
feat(postman): add folders for postman collections + postman types (#624)Co-authored-by: Alberto García Hierro <alberto@garciahierro.com> Co-authored-by: Dustin Deus <deusdustin@gmail.com>

### PR DESCRIPTION
**Pull request by andreimc**
feat(postman): add folders for postman collections and add types

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by andreimc** [comment]
This is complete it generates both folders and single gql files.

**Comment by Aenimus** [comment]
@andreimc Hi,

This looks awesome. I'm gonna have a closer look into it tomorrow--sorry for the delay.

Great work!

**Comment by fiam** [comment]
@andreimc This looks very nice. For anyone wondering why the PR has bundled types for postman, please look at this [issue](https://github.com/postmanlabs/postman-collection/issues/602). TLDR: They don't have the bandwidth to get the updates types submitted to DefinitelyTyped, so what you install from `@types/postman-collections` are incorrect.

As for the PR, it looks good to me. Please, update the PR with the latest changes from main (we can do this for you if you want to) and then we'll merge it.

**Review by fiam — APPROVED** [review]
LGTM

**Comment by fiam** [comment]
This is how the operations look like with `testapps/default`

image

**Pull request merged**
