### PR TITLE
docs: make headings sharable

### PR DESCRIPTION
**Pull request by Pagebakers**
#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jensneuse** [comment]
When I click on a headline, the scroll position is wrong because of the nav bar. (The nav bar covers the headline)
When clicking a headline, the full headline should be visible.

I also noticed that subheadings are only clickable when the TOC is activated.
If TOC is hidden, headings are not clickable.
I think they should always be clickable.

**Comment by Pagebakers** [comment]
> When I click on a headline, the scroll position is wrong because of the nav bar. (The nav bar covers the headline) When clicking a headline, the full headline should be visible.
> 
> I also noticed that subheadings are only

https://user-images.githubusercontent.com/32583/180944920-4dcc756a-00ea-445b-8da5-184419739ad4.mov

 clickable when the TOC is activated. If TOC is hidden, headings are not clickable. I think they should always be clickable.

Now that you mention, the header is also too high when scrolling, as it renders over the sidenav

**Comment by Pagebakers** [comment]
All fixed, including the scroll issue

**Comment by jensneuse** [comment]
@Pagebakers when you click on this link https://wundergraph-docs-git-eelco-eng-200-docs-mak-088697-wunder-graph.vercel.app/getting-started it's not possible for me to click on the headlines

**Comment by Pagebakers** [comment]
Ready

**Comment by jensneuse** [comment]
@Pagebakers where did the code box at the top go?
https://wundergraph-docs-git-eelco-eng-200-docs-mak-088697-wunder-graph.vercel.app/

**Pull request merged**
