### PR TITLE
fix: do not inject empty queries (#718)Co-authored-by: Sergiy <818351+devsergiy@users.noreply.github.com> Co-authored-by: Eelco Wiersma <contact@pagebakers.nl> Co-authored-by: Alberto García Hierro <alberto@garciahierro.com>

### PR DESCRIPTION
**Pull request by erguotou520**
When `hasInternalMutations` is true but `internalMutations` is empty, this will generate unexpected properties on `Mutations`, this will cause the error code `internalClient.mutations.mutations`. So leave it empty.

#### Checklist

- [ ] run `make test`
- [ ] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Pagebakers — APPROVED** [review]
Thanks! That else clause shouldn't be there indeed.

**Review by fiam — APPROVED** [review]
LGTM

**Comment by jensneuse** [comment]
@fiam if you've tested this locally, please merge.

**Comment by fiam** [comment]
@jensneuse  Tested locally, works as expected

**Pull request merged**
