### PR TITLE
feat: allow to init wundergraph into existing projects

### PR DESCRIPTION
**Pull request by JivusAyrus**
#### Checklist

- [ ] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by fiam** [comment]
Looks good to me, but I’m not sure about using the simple example for that (there might be links to it that we need to update). Maybe we could add a dedicated one for this?

**Comment by JivusAyrus** [comment]
We can add a new one also. But thought it wouldn't be any different from simple.

**Comment by fiam** [comment]
> Looks good to me, but I’m not sure about using the simple example for that (there might be links to it that we need to update). Maybe we could add a dedicated one for this?

Replying to myself: the simple example is still working in this PR, but some deprecated parts are removed. All good!

**Review by fiam — APPROVED** [review]

**Review by Pagebakers — APPROVED** [review]
Love it

**Pull request merged**
