### PR TITLE
feat: use .cjs extension for commonjs to support esm projects

### PR DESCRIPTION
**Pull request by Pagebakers**
#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

This PR make sure wunderctl up/generate output all .js files in the bundle with .cjs extension. This makes the output compatible with ESM projects.

### CODE REVIEW

**Review by StarpTech — CHANGES_REQUESTED** [review]
I'd not merge it until we understand the full impact. Testing examples, documenting the migration etc...

**Comment by Pagebakers** [comment]
Yep nextjs testapp works, default testapp works, vite testapp works (with both esm and commonjs).

Technically it doesn't change anything, just the file extension from .js to .cjs for all generated files in .wundergraph/generated.

**Review by StarpTech — APPROVED** [review]
LGTM

**Review by fiam — APPROVED** [review]
I've tested this locally and ran the examples CI, both seem to work https://github.com/wundergraph/wundergraph/actions/runs/4532470716

**Pull request merged**
