### PR TITLE
fix: don't (re-)fetch user server & client-side when authentication is disabled

### PR DESCRIPTION
**Pull request by jensneuse**
This PR improves the nextjs package.

When no authentication provider is configured (cookie based auth), there's no need to fetch the user server-side as well as client-side, incl. re-fetching. This PR disables all user fetches in this case.

### CODE REVIEW

**Comment by StarpTech** [comment]
Is it possible to implement it in the same way for the wundergraph client?

**Comment by jensneuse** [comment]
> Is it possible to implement it in the same way for the wundergraph client?

The client by itself doesn't refetch. It's the nextjs wrapper that does by handling the application lifecycle with hooks.

**Comment by StarpTech** [comment]
I mean to avoid [this](https://github.com/wundergraph/wundergraph/blob/main/packages/sdk/src/codegen/templates/typescript/web.client.template.ts#L266) when no auth was configured.

**Comment by jensneuse** [comment]
> I mean to avoid [this](https://github.com/wundergraph/wundergraph/blob/main/packages/sdk/src/codegen/templates/typescript/web.client.template.ts#L266) when no auth was configured.

It's a different client btw. has nothing to do with nextjs. Won't fix in this PR.

**Comment by StarpTech** [comment]
ok

**Review by StarpTech — APPROVED** [review]
LGTM

**Pull request merged**
