### PR TITLE
chore: re-enable hook tests

### PR DESCRIPTION
**Pull request by fiam**
Disabled in #689

Fixes ENG-1427

### CODE REVIEW

**Comment by fiam** [comment]
@devsergiy @jensneuse could you please clarify why these were disabled? They seem to work just fine https://github.com/wundergraph/wundergraph/actions/runs/4281385067/jobs/7454343455#step:14:405

**Comment by devsergiy** [comment]
Hey @fiam 

they were failing in that branch

**Comment by devsergiy** [comment]
and sometimes recursive tests going into recursion which leads to endless pipeline, not sure why
it is not happening always

**Comment by fiam** [comment]
@devsergiy The problem has nothing to do with these tests. Notice this run from another PR, it hung up with these tests disabled https://github.com/wundergraph/wundergraph/actions/runs/4297274809/jobs/7490040921 - It seems to me like the hooks server not exiting properly sometimes (we have a workaround for that in the testing SDK, but it might not be reliably enough)

**Review by devsergiy — APPROVED** [review]

**Review by StarpTech — APPROVED** [review]
LGTM

**Pull request merged**
