### PR TITLE
docs: add keycloak role mapping instructions

### LINKED ISSUE #1084: Consider populating User.roles from token
I do not know that problem exist when keycloak jwt is parsed in wundergraph....The array roles is not populate..role attribute comes with null value....For fix this situation i use this hook:
```
authentication: {
     mutatingPostAuthentication: async ({ user }) => {
              console.log("===Autenticacion===")
              console.log(user.roles)
              if  (user.roles === null) {
                if (user.accessToken) {
                    console.log(user.accessToken.roles)
                    user.roles = Object.values(user.accessToken.roles)

                }
              }
              console.log(user.roles)

              return {
                user,
                status: 'ok',
              };
            },
          },
```
With this senteces i populate the property roles in user object:
user.roles = Object.values(user.accessToken.roles)
I will want that wundergraph teams will review because the property roles is not populate if in jwt in delivered for keycloak comes with attribute roles like as arrays of strings?

I suggest using the same pattern used by Hasura configuring special claims like "x-hasura-allowed-roles" in wundergraph could be "x-wundergraph-allowed-roles". https://hasura.io/docs/latest/auth/authentication/jwt/

### PR DESCRIPTION
**Pull request by ShaneMaglangit**
## Motivation and Context

Resolves #1084 where User.roles isn't getting populated due to incomplete Keycloak configuration.

**Resolution:**

- Updated the README.md of the Keycloak example.
- Modified keycloak-openid-connect-authentication.md in the documentation.

Added instructions on how to configure Keycloak's mapper and propagate realm/client roles directly into User.roles.

#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [x] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

/claim #1084

### CODE REVIEW

**Comment by ShaneMaglangit** [comment]
Hi @fiam, I would appreciate your review of this PR that should resolve https://github.com/wundergraph/wundergraph/issues/1084

**Review by Pagebakers — APPROVED** [review]
LGTM

**Review by fiam — APPROVED** [review]
LGTM

**Comment by fiam** [comment]
Thanks for your contribution @ShaneMaglangit!

**Pull request merged**
