### PR TITLE
feat: add ability for the user to comment on the documentation

### PR DESCRIPTION
**Pull request by JivusAyrus**
#### Checklist

- [x] run `make test`
- [x] PR title must follow [conventional-commit-standard](https://github.com/wundergraph/wundergraph/blob/main/CONTRIBUTING.md#conventional-commit-standard)
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Code of conduct](https://github.com/wundergraph/wundergraph/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by StarpTech** [comment]
The preview doesn't seem to work.

**Comment by JivusAyrus** [comment]
> The preview doesn't seem to work.

Sorry have to add envs in Vercel

**Comment by JivusAyrus** [comment]
Don't think it would work in the preview as it's a different domain.
giscus.wundergraph.com has frame-ancestors as 'self'

**Comment by StarpTech** [comment]
Fine for me if it is working on prod.

**Review by StarpTech — APPROVED** [review]
LGTM

**Comment by jensneuse** [comment]
Just one question. Would it make sense to start discussions on this repo with the topic docs? This way we keep it all in one place. Website docs can go into the other repo.

**Comment by JivusAyrus** [comment]
That's what I thought initially.
What do you mean by "Website docs can go into the other repo."?

**Comment by jensneuse** [comment]
> That's what I thought initially. What do you mean by "Website docs can go into the other repo."?

We have one repo (https://github.com/wundergraph/comments) where we put the comments for the website (wundergraph.com).

Should the comments on docs.wundergraph.com be handled on this repo here (wundergraph/wundergraph) or should they also go on the wundergraph/comments repo?

**Comment by JivusAyrus** [comment]
I would prefer wundergraph/wundergraph. We can create a "Docs" category in discussions.

**Pull request merged**
