### PR TITLE
fix: don't swallow errors in wunderctl loadoperations

### PR DESCRIPTION
**Pull request by fiam**
Always return the Output to the caller, then convert it to string
before printing. Return zero in all cases, since the TS side uses the
exit code to determine wether to parse the outout or print it as a raw
error.

### CODE REVIEW

**Comment by jensneuse** [comment]
Instead of this PR, I'd rather abandon the idea of trying to fix this approach here, I'd go with ENG-649.

**Comment by fiam** [comment]
> Instead of this PR, I'd rather abandon the idea of trying to fix this approach here, I'd go with ENG-649.

This would be a subset of ENG-649

**Review by StarpTech — CHANGES_REQUESTED** [review]
Can we provide a basic test for this?

**Comment by fiam** [comment]
> Can we provide a basic test for this?

Not sure if it's worth the hassle at this point, because however takes ENG-649 might decide to redesign the API.

**Comment by fiam** [comment]
Closed in favour of ENG-649

**Pull request closed without merging**
